environment:
  nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script:
  - node --version
  - yarn --version
  - yarn test
  - yarn lint

cache:
 - "%LOCALAPPDATA%\\Yarn"

build: off